CREATE DATABASE IF NOT EXISTS restaurante_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE restaurante_db;
-- CLIENTES (OBRIGATÓRIO)
CREATE TABLE customers (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
phone VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
-- MESAS (OBRIGATÓRIO)
CREATE TABLE tables (
id INT AUTO_INCREMENT PRIMARY KEY,
table_number INT NOT NULL UNIQUE,
capacity INT NOT NULL,
status ENUM('ATIVA', 'INATIVA') DEFAULT 'ATIVA',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
-- RESERVAS (BÔNUS)
CREATE TABLE reservations (
id INT AUTO_INCREMENT PRIMARY KEY,
customer_id INT NOT NULL,
table_id INT NOT NULL,
reservation_datetime DATETIME NOT NULL,
status ENUM('PENDENTE', 'CONFIRMADA', 'CANCELADA') DEFAULT 'PENDENTE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT fk_res_customer FOREIGN KEY (customer_id)
REFERENCES customers(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT fk_res_table FOREIGN KEY (table_id)
REFERENCES tables(id)
ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;
